// Generated by CoffeeScript 1.9.3
var app, bodyParser, compress, express, http2, methodOverride, morgan, myEnv, oneDay, portNumber, server, serverOptions;

myEnv = process.env.NODE_ENV || 'development';

bodyParser = require('body-parser');

compress = require('compression');

express = require('express');

http2 = require('http2');

methodOverride = require('method-override');

morgan = require('morgan');

oneDay = 86400000;

app = express();

app.set('views', __dirname + '../app/views');

app.engine('html', require('ejs').renderFile);

app.use(compress());

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(methodOverride());

app.use(express["static"](__dirname + '/../app'));

serverOptions = {
  key: fs.readFileSync('ssl/or.key'),
  cert: fs.readFileSync('ssl/or.crt'),
  requestCert: true,
  passphrase: 'when is your orientation week'
};

server = http2.createServer(serverOptions, app);

portNumber = 5491;

server.listen(portNumber, function() {
  return console.log("Orientation week application now running -- server listening on port %d in mode %s".underline.green, portNumber, app.settings.env);
});
